apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    buildToolsVersion '30.0.2'

    defaultConfig {
        applicationId 'top.ximin.epdwallpaper'
        minSdkVersion 27
        targetSdkVersion 27
        versionCode 2
        versionName '1.0.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    lintOptions {
        abortOnError false
    }
}

dependencies {
    compileOnly files('libs/api-82.jar')
}
